version: "3"
services:
  authserver:
    image: segence/chartmuseum-authserver:${VERSION}
    ports:
      - "5001:5001"
    volumes:
      - "./authserver:/go/src/github.com/chartmuseum/auth-server-example/authserver:ro"
      - "./key.pem:/key.pem:ro"
    command: --private-key-path=/key.pem --service-port=5001
  chartmuseum:
    image: chartmuseum/chartmuseum:latest
    ports:
      - "8080:8080"
    environment:
      - "DEBUG=1"
      - "DEPTH=2"
      - "ALLOW_OVERWRITE=1"
      - "STORAGE=local"
      - "STORAGE_LOCAL_ROOTDIR=/charts"
      - "BEARER_AUTH=1"
      - "AUTH_REALM=http://localhost:5001/oauth/token"
      - "AUTH_SERVICE=localhost:5001"
      - "AUTH_CERT_PATH=/public.pem"
    volumes:
      - "./public.pem:/public.pem:ro"
